memory_limit = 1024M
max_execution_time = 600
upload_max_filesize = 128M
post_max_size = 128M
date.timezone = Asia/Karachi

display_errors = Off
display_startup_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
